name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # 匹配 v0.0.1, v1.2.3 等格式的标签

env:
  GO_VERSION: "1.21"
  MANIFEST_URL: "https://storage.bizyair.cn/cli/releases/manifest.json"

jobs:
  prepare:
    name: 准备版本号
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.determine_version.outputs.version }}
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 确定版本号
        id: determine_version
        run: |
          # 使用 Git Tag 作为版本号
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
            echo "使用 Git Tag 版本号: $VERSION"
          else
            echo "错误: 此工作流只能通过 tag 触发"
            exit 1
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build:
    name: 构建 ${{ matrix.goos }}-${{ matrix.goarch }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 构建二进制文件
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # 确定文件名
          PLATFORM="${GOOS}-${GOARCH}"
          # 将 darwin 转换为 macos
          if [ "$GOOS" = "darwin" ]; then
            PLATFORM="macos-${GOARCH}"
          fi

          if [ "$GOOS" = "windows" ]; then
            FILENAME="bizyair-${VERSION}-${PLATFORM}.exe"
          else
            FILENAME="bizyair-${VERSION}-${PLATFORM}"
          fi

          echo "构建 ${PLATFORM} 版本..."

          # 构建
          CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build \
            -ldflags "-w -s -X 'github.com/siliconflow/bizyair-cli/meta.Version=${VERSION}' -X 'github.com/siliconflow/bizyair-cli/meta.Commit=${GITHUB_SHA::7}' -X 'github.com/siliconflow/bizyair-cli/meta.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" \
            -a -tags=netgo \
            -o "dist/${FILENAME}" \
            main.go

          # 计算 SHA256
          cd dist
          sha256sum "${FILENAME}" | awk '{print $1}' > "${FILENAME}.sha256"

          echo "构建完成: ${FILENAME}"
          ls -lh "${FILENAME}"

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  upload:
    name: 上传到 OSS
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          merge-multiple: true
          path: dist

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          pip install requests alibabacloud-oss-v2 alibabacloud-credentials

      - name: 上传到 OSS 并生成 manifest
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          API_KEY: ${{ secrets.BIZYAIR_API_KEY }}
          BASE_DOMAIN: ${{ secrets.BIZYAIR_BASE_DOMAIN || 'https://api.bizyair.cn' }}
        run: |
          python tools/upload_release.py

      - name: 显示上传结果
        run: |
          echo "✅ 版本 ${{ needs.prepare.outputs.version }} 已成功发布"
          echo "Manifest URL: ${{ env.MANIFEST_URL }}"
